fun main(args: Array<String>) {
    val linkList = LinkList<Int>()
//    linkList.add(2)
//    linkList.add(3,1)
//    linkList.add(4)
//    linkList.add(5,1)
    linkList.add(0)
    linkList.add(0)
    linkList.add(4,2)
    linkList.add(0)
    linkList.removeAt(2)
    linkList.print()
    println()
    println(linkList.size)
}